[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/mkielar/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager fluidd-config]
type: git_repo
primary_branch: master
path: ~/fluidd-config
origin: https://github.com/fluidd-core/fluidd-config.git
managed_services: klipper

[update_manager fluidd]
type: web
channel: stable
repo: fluidd-core/fluidd
path: ~/fluidd

[power sonoff]
type: homeassistant
address: 192.168.0.177
device: switch.voronpower_voron_power
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4NjNlOWE0NWJjNDg0NjFiOTNjOGNlZWMwOWMwY2FiYyIsImlhdCI6MTcwNzEzNzI2NiwiZXhwIjoyMDIyNDk3MjY2fQ.KkThri_Q4TJBr0cBvYNb3fD1rsTLzLUvwg4cjat2cS8
[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main